version: 2

node_6: &node_6
  docker:
    - image: node:6@sha256:c1f7fbd0834eed5e69ea8e925ab59be61e68f278258df7cbbd652cb5516aacb7

node_8: &node_8
  docker:
    - image: node:8@sha256:9a42112281bef142cd40a281c5cd1b781cc9d0f0f2314827b87f86893f636df6

node_next: &node_next
  docker:
    - image: node:latest@sha256:4528053a3d47aeff399dcd19cb86dda3d58b42521bf992093267672b29313036

test_plan: &test_plan
  steps:
    - checkout
    - restore_cache:
        keys:
          - v1-dependencies_test_plan
    - run: yarn install --frozen-lockfile
    - save_cache:
        paths:
          - node_modules
          - ${HOME}/.cache/yarn
        key: v1-dependencies_test_plan
    - run: yarn test
    - run: $(yarn bin)/codecov || echo "CodeCov did not collect coverage reports"

jobs:
  node_6_test_plan:
    <<: [*node_6, *test_plan]
  node_8_test_plan:
    <<: [*node_8, *test_plan]
  node_next_test_plan:
    <<: [*node_next, *test_plan]

workflows:
  version: 2
  build:
    jobs:
      - node_6_test_plan
      - node_8_test_plan
      - node_next_test_plan
