version: 2

node_6: &node_6
  docker:
    - image: node:6@sha256:2dfba7da0332b7e3356829c140e092d2fc74bb5cdfbb0349275645f6d4368f1b

node_8: &node_8
  docker:
    - image: node:8@sha256:ed6fcd891903ce10e9a557aa1600390900fc60952272d98b6bb105b39ad4967d

node_next: &node_next
  docker:
    - image: node:latest@sha256:f605ae71dd942b307c91639ecb620d943631a0ad29bebcf290c546c1d5beb9c1

test_plan: &test_plan
  steps:
    - checkout
    - restore_cache:
        keys:
          - v1-dependencies_test_plan
    - run: yarn install --frozen-lockfile
    - save_cache:
        paths:
          - node_modules
          - ${HOME}/.cache/yarn
        key: v1-dependencies_test_plan
    - run: yarn test
    - run: $(yarn bin)/codecov || echo "CodeCov did not collect coverage reports"

jobs:
  node_6_test_plan:
    <<: [*node_6, *test_plan]
  node_8_test_plan:
    <<: [*node_8, *test_plan]
  node_next_test_plan:
    <<: [*node_next, *test_plan]

workflows:
  version: 2
  build:
    jobs:
      - node_6_test_plan
      - node_8_test_plan
      - node_next_test_plan
