version: 2

node_6: &node_6
  docker:
    - image: node:6@sha256:51fc4ee21ff533b39abe6f4a3a999b0dde51e5744c8e1970c6c9c5f9a5976f3c

node_8: &node_8
  docker:
    - image: node:8@sha256:3d43ad1b3a743305d31ac5524193e8734a79185f6968057a997c28be78881abe

node_next: &node_next
  docker:
    - image: node:latest@sha256:b6bea9475e671db8b3e72a52423c80a57e2c222aa5cd8f01dc6387c719f19ca7

test_plan: &test_plan
  steps:
    - checkout
    - restore_cache:
        keys:
          - v1-dependencies_test_plan
    - run: yarn install --frozen-lockfile
    - save_cache:
        paths:
          - node_modules
          - ${HOME}/.cache/yarn
        key: v1-dependencies_test_plan
    - run: yarn test
    - run: $(yarn bin)/codecov || echo "CodeCov did not collect coverage reports"

jobs:
  node_6_test_plan:
    <<: [*node_6, *test_plan]
  node_8_test_plan:
    <<: [*node_8, *test_plan]
  node_next_test_plan:
    <<: [*node_next, *test_plan]

workflows:
  version: 2
  build:
    jobs:
      - node_6_test_plan
      - node_8_test_plan
      - node_next_test_plan
