version: 2

node_6: &node_6
  docker:
    - image: node:6@sha256:2ea7a1af89a198dd0c74b1604255a82b8bbf72793956b0424f9ef68db0cd5b66

node_8: &node_8
  docker:
    - image: node:8@sha256:de151851364686c32c74c31345e8e3e5db4e9fb93869f706412b50f20ab2ef8d

node_next: &node_next
  docker:
    - image: node:latest@sha256:88df058059e456a409f9ffd0c70fc898840be0c91a41d548c41bc4f6e0192b7f

test_plan: &test_plan
  steps:
    - checkout
    - restore_cache:
        keys:
          - v1-dependencies_test_plan
    - run: yarn install --frozen-lockfile
    - save_cache:
        paths:
          - node_modules
          - ${HOME}/.cache/yarn
        key: v1-dependencies_test_plan
    - run: yarn test
    - run: $(yarn bin)/codecov || echo "CodeCov did not collect coverage reports"

jobs:
  node_6_test_plan:
    <<: [*node_6, *test_plan]
  node_8_test_plan:
    <<: [*node_8, *test_plan]
  node_next_test_plan:
    <<: [*node_next, *test_plan]

workflows:
  version: 2
  build:
    jobs:
      - node_6_test_plan
      - node_8_test_plan
      - node_next_test_plan
