version: 2

node_6: &node_6
  docker:
    - image: node:6@sha256:be61977906abc9d0e97def07dfeaa9e411df08ce8ff8e8efd70da6c3e977cad5

node_8: &node_8
  docker:
    - image: node:8@sha256:287b8a533675e0c72cb374b5e5ab580961b2a203600e1758b95c475390bd9f9a

node_next: &node_next
  docker:
    - image: node:latest@sha256:064e5cd024878466b7de0d9fdc2ac5f79d5f526a5b6fe53ad8ab2cd3b3589418

test_plan: &test_plan
  steps:
    - checkout
    - restore_cache:
        keys:
          - v1-dependencies_test_plan
    - run: yarn install --frozen-lockfile
    - save_cache:
        paths:
          - node_modules
          - ${HOME}/.cache/yarn
        key: v1-dependencies_test_plan
    - run: yarn test
    - run: $(yarn bin)/codecov || echo "CodeCov did not collect coverage reports"

jobs:
  node_6_test_plan:
    <<: [*node_6, *test_plan]
  node_8_test_plan:
    <<: [*node_8, *test_plan]
  node_next_test_plan:
    <<: [*node_next, *test_plan]

workflows:
  version: 2
  build:
    jobs:
      - node_6_test_plan
      - node_8_test_plan
      - node_next_test_plan
