version: 2

node_6: &node_6
  docker:
    - image: node:6@sha256:4cdd9c14c85fee47fc48f5f660949ba761992f97abdf523161e110e63821a77c

node_8: &node_8
  docker:
    - image: node:8@sha256:918f0be3932f555cd2645ca828b9c231a2dab10d9cf2dbb58896411207bbe52f

node_next: &node_next
  docker:
    - image: node:latest@sha256:02671bb60e5213b9fabda4e078783db86b2cf97ed996f9198a40411fb2639721

test_plan: &test_plan
  steps:
    - checkout
    - restore_cache:
        keys:
          - v1-dependencies_test_plan
    - run: yarn install --frozen-lockfile
    - save_cache:
        paths:
          - node_modules
          - ${HOME}/.cache/yarn
        key: v1-dependencies_test_plan
    - run: yarn test
    - run: $(yarn bin)/codecov || echo "CodeCov did not collect coverage reports"

jobs:
  node_6_test_plan:
    <<: [*node_6, *test_plan]
  node_8_test_plan:
    <<: [*node_8, *test_plan]
  node_next_test_plan:
    <<: [*node_next, *test_plan]

workflows:
  version: 2
  build:
    jobs:
      - node_6_test_plan
      - node_8_test_plan
      - node_next_test_plan
