version: 2

node_6: &node_6
  docker:
    - image: node:6@sha256:03c5a8a507f6e3e975b0300b0206e92cf89161649ee02292a2741c9e0856b056

node_8: &node_8
  docker:
    - image: node:8@sha256:1bf3f5613c27397bdda5e0da84641ea1e925822e5f3a820f00ced2c31ff75a2a

node_next: &node_next
  docker:
    - image: node:latest@sha256:97350924b7e635b01849c7a251b49b5b694d2541c36256977db0f47a6bee4dc3

test_plan: &test_plan
  steps:
    - checkout
    - restore_cache:
        keys:
          - v1-dependencies_test_plan
    - run: yarn install --frozen-lockfile
    - save_cache:
        paths:
          - node_modules
          - ${HOME}/.cache/yarn
        key: v1-dependencies_test_plan
    - run: yarn test
    - run: $(yarn bin)/codecov || echo "CodeCov did not collect coverage reports"

jobs:
  node_6_test_plan:
    <<: [*node_6, *test_plan]
  node_8_test_plan:
    <<: [*node_8, *test_plan]
  node_next_test_plan:
    <<: [*node_next, *test_plan]

workflows:
  version: 2
  build:
    jobs:
      - node_6_test_plan
      - node_8_test_plan
      - node_next_test_plan
