version: 2

node_6: &node_6
  docker:
    - image: node:6@sha256:38bc9ed8dd3a7f3cdb8d3d9ac751158f2ef43ec6704514589c1c28e9169ba1c7

node_8: &node_8
  docker:
    - image: node:8@sha256:5adc5390d0f03538decf668646804d00f4637caa099ae0c4eb77337ad507511e

node_next: &node_next
  docker:
    - image: node:latest@sha256:9b6cdb52e2f86ce667f0dcc68b8dcc4e1e9be84b49111196cd4cf51081548692

test_plan: &test_plan
  steps:
    - checkout
    - restore_cache:
        keys:
          - v1-dependencies_test_plan
    - run: yarn install --frozen-lockfile
    - save_cache:
        paths:
          - node_modules
          - ${HOME}/.cache/yarn
        key: v1-dependencies_test_plan
    - run: yarn test
    - run: $(yarn bin)/codecov || echo "CodeCov did not collect coverage reports"

jobs:
  node_6_test_plan:
    <<: [*node_6, *test_plan]
  node_8_test_plan:
    <<: [*node_8, *test_plan]
  node_next_test_plan:
    <<: [*node_next, *test_plan]

workflows:
  version: 2
  build:
    jobs:
      - node_6_test_plan
      - node_8_test_plan
      - node_next_test_plan
