version: 2

node_6: &node_6
  docker:
    - image: node:6@sha256:6682a6954570e89a05756c23f763e2cd114f35a2f5ccfb7fbe312c51cbee26fd

node_8: &node_8
  docker:
    - image: node:8@sha256:16494f628a1b093eca32f8a19c499b64b800bc310a72bc6a64da92a7aad7bfb6

node_next: &node_next
  docker:
    - image: node:latest@sha256:45aab27018267562e1c5bcad8c2e0d63a88f00be5c3f2348190bc62336abf727

test_plan: &test_plan
  steps:
    - checkout
    - restore_cache:
        keys:
          - v1-dependencies_test_plan
    - run: yarn install --frozen-lockfile
    - save_cache:
        paths:
          - node_modules
          - ${HOME}/.cache/yarn
        key: v1-dependencies_test_plan
    - run: yarn test
    - run: $(yarn bin)/codecov || echo "CodeCov did not collect coverage reports"

jobs:
  node_6_test_plan:
    <<: [*node_6, *test_plan]
  node_8_test_plan:
    <<: [*node_8, *test_plan]
  node_next_test_plan:
    <<: [*node_next, *test_plan]

workflows:
  version: 2
  build:
    jobs:
      - node_6_test_plan
      - node_8_test_plan
      - node_next_test_plan
