version: 2

node_6: &node_6
  docker:
    - image: node:6@sha256:662700686bc87f720b0a2332ef5342f408607c389a8e1ee0dc045f478d04b772

node_8: &node_8
  docker:
    - image: node:8@sha256:459076aaf169a1387f91eb762b841167788debc92752855938b449c110ae7f6e

node_next: &node_next
  docker:
    - image: node:latest@sha256:5087e65a8819e940256d8038a853cffdb67b669f246df47e672e8ae99b08c692

test_plan: &test_plan
  steps:
    - checkout
    - restore_cache:
        keys:
          - v1-dependencies_test_plan
    - run: yarn install --frozen-lockfile
    - save_cache:
        paths:
          - node_modules
          - ${HOME}/.cache/yarn
        key: v1-dependencies_test_plan
    - run: yarn test
    - run: $(yarn bin)/codecov || echo "CodeCov did not collect coverage reports"

jobs:
  node_6_test_plan:
    <<: [*node_6, *test_plan]
  node_8_test_plan:
    <<: [*node_8, *test_plan]
  node_next_test_plan:
    <<: [*node_next, *test_plan]

workflows:
  version: 2
  build:
    jobs:
      - node_6_test_plan
      - node_8_test_plan
      - node_next_test_plan
