version: 2

node_6: &node_6
  docker:
    - image: node:6@sha256:4f404b01ad504f0f0c625ae60498eb0fee564ea2bea5b6d902285e515ca680cf

node_8: &node_8
  docker:
    - image: node:8@sha256:fecc38a3579eb06c9e447a1172b8ce703a8d4d8f122c938128dd81ef5de76ab3

node_next: &node_next
  docker:
    - image: node:latest@sha256:0b3c807e3aea66d29933a6f9257f839ba44963f16675886d2906cd0a2fc49758

test_plan: &test_plan
  steps:
    - checkout
    - restore_cache:
        keys:
          - v1-dependencies_test_plan
    - run: yarn install --frozen-lockfile
    - save_cache:
        paths:
          - node_modules
          - ${HOME}/.cache/yarn
        key: v1-dependencies_test_plan
    - run: yarn test
    - run: $(yarn bin)/codecov || echo "CodeCov did not collect coverage reports"

jobs:
  node_6_test_plan:
    <<: [*node_6, *test_plan]
  node_8_test_plan:
    <<: [*node_8, *test_plan]
  node_next_test_plan:
    <<: [*node_next, *test_plan]

workflows:
  version: 2
  build:
    jobs:
      - node_6_test_plan
      - node_8_test_plan
      - node_next_test_plan
