version: 2

node_6: &node_6
  docker:
    - image: node:6@sha256:9de20d4f3627de8101d7d3f5055ca333ad0a1b547fa111be95d23faac5b0863b

node_8: &node_8
  docker:
    - image: node:8@sha256:021180e0b79e02d85c4d449c1a17ddb2222d978db5f2aa4d37e6e25832fe6a68

node_next: &node_next
  docker:
    - image: node:latest@sha256:6ef2422607bf8303dd6747cdf47c97f3687a21a58453a80c137d4deb31d55be8

test_plan: &test_plan
  steps:
    - checkout
    - restore_cache:
        keys:
          - v1-dependencies_test_plan
    - run: yarn install --frozen-lockfile
    - save_cache:
        paths:
          - node_modules
          - ${HOME}/.cache/yarn
        key: v1-dependencies_test_plan
    - run: yarn test
    - run: $(yarn bin)/codecov || echo "CodeCov did not collect coverage reports"

jobs:
  node_6_test_plan:
    <<: [*node_6, *test_plan]
  node_8_test_plan:
    <<: [*node_8, *test_plan]
  node_next_test_plan:
    <<: [*node_next, *test_plan]

workflows:
  version: 2
  build:
    jobs:
      - node_6_test_plan
      - node_8_test_plan
      - node_next_test_plan
